export type Decision = { title: string; body: string; tradeoff: string };
export type Project = { slug: string; index: string; name: string; tagline: string; summary: string; year: string; role: string; category: string; featured: boolean; stack: string[]; links: { live?: string; repo?: string; note?: string }; problem: string; brief: string[]; decisions: Decision[]; outcomes: { value: string; label: string }[]; limits: string[] };

const shared = {
  decisions: [
    { title: "The interface starts with the user’s next decision", body: "The first screen is structured around what someone came to do, not around everything the product can say. Supporting information is available without competing with that first action.", tradeoff: "A focused surface has less room for secondary content, but it makes the primary path easier to understand." },
    { title: "Customer and operator flows belong to one system", body: "The public experience and the work behind it were considered together. A polished customer surface is only useful if the people operating the product can keep it accurate.", tradeoff: "Thinking beyond the marketing page takes longer, but it produces a more honest product." },
    { title: "Responsive behaviour is part of the feature", body: "The layouts are designed for the phone first, then expanded for larger screens. Clear hierarchy and touch-friendly actions matter more than simply shrinking a desktop layout.", tradeoff: "Desktop has less decorative space, but the core task remains immediate on the device most users carry." },
  ],
};

export const projects: Project[] = [
  { slug: "foodician", index: "01", name: "Foodician", tagline: "A restaurant platform built around the real work of hospitality", summary: "A complete restaurant platform covering digital menus, table reservations, ordering and a real-time admin dashboard — designed to make the customer experience and the operational experience feel like one system.", year: "2026", role: "Frontend & Full-stack developer", category: "Restaurant · Product platform", featured: true, stack: ["React", "JavaScript", "Tailwind CSS", "APIs", "Vercel"], links: { live: "https://treatsbyfoodician.com.ng/", repo: "https://github.com/0xEmmo/foodician-app" }, problem: "A restaurant site cannot stop at a menu. Someone still needs to manage tables, orders and the changing details behind the page a customer sees. The product had to make the front-of-house experience feel simple while giving the team a useful control surface.", brief: ["A digital menu that puts food and key information in front of customers quickly.", "Table reservations and ordering flows designed for mobile use.", "An admin surface for managing the operational details behind the public experience."], decisions: shared.decisions, outcomes: [{ value: "Live", label: "public restaurant experience" }, { value: "01", label: "connected product across customer and admin flows" }, { value: "Mobile", label: "first interface priority" }], limits: ["The exact operational metrics are private, so this case study focuses on product decisions rather than invented performance claims.", "The next layer is continuing to improve reporting and operational visibility for the team behind the experience."] },
  { slug: "lagos-live", index: "02", name: "Lagos Live", tagline: "Real-time nightlife discovery for a city that does not sit still", summary: "A mobile-first discovery platform for parties, clubs, venues and DJs, with search, filters, maps and saved events in one interface.", year: "2026", role: "Frontend developer", category: "Events · Discovery platform", featured: true, stack: ["React", "JavaScript", "Vite", "Tailwind CSS", "Maps"], links: { live: "https://lagos-live.vercel.app/", repo: "https://github.com/0xEmmo/LagosLive" }, problem: "Lagos nightlife information is scattered across posts, stories, chats and venue pages. The product needed to help someone move from vague intent — somewhere to go tonight — to a specific event without making them search the whole internet.", brief: ["Browse events and venues in a quick, readable mobile interface.", "Use search and filters to narrow a busy city down to the right night.", "Bring location, saved events and discovery into one consistent flow."], decisions: shared.decisions, outcomes: [{ value: "Live", label: "public events discovery product" }, { value: "Mobile", label: "primary browsing context" }, { value: "Lagos", label: "city-specific product focus" }], limits: ["Event data changes quickly, so freshness and moderation remain ongoing product work.", "The next improvements are deeper event detail, stronger sharing and more ways for organisers to manage listings."] },
  { slug: "deans-cup", index: "03", name: "Dean’s Cup FPL", tagline: "Fantasy football for a real university community", summary: "A fantasy football platform built for UNILAG with squad management, live scoring, leaderboards and an admin dashboard.", year: "2026", role: "Frontend & full-stack developer", category: "Sport · Full-stack platform", featured: true, stack: ["React", "JavaScript", "Full-stack", "Dashboards", "Vercel"], links: { live: "https://pessadeans.vercel.app/", repo: "https://github.com/0xEmmo/deans-cup-fantasy" }, problem: "A fantasy league is only fun when the rules, scores and standings feel trustworthy. The platform needed to make the game easy for students to join while giving organisers enough control to keep the competition moving.", brief: ["Create and manage squads in a clear fantasy football flow.", "Surface points, fixtures and leaderboards so the competition stays visible.", "Give organisers a dashboard for the parts players should not have to manage."], decisions: shared.decisions, outcomes: [{ value: "Live", label: "university fantasy league" }, { value: "2", label: "player and admin surfaces" }, { value: "Real-time", label: "scoring and leaderboard focus" }], limits: ["The platform is tied to the competition’s current operating rules, which need to evolve with each season.", "The next step is deeper notifications and richer historical performance views for players."] },
  { slug: "retrospacer", index: "04", name: "RETROSPACER", tagline: "A cosmic e-commerce experience for Lagos street culture", summary: "A full-stack streetwear storefront with a product catalogue, cart, checkout, auth and admin panel wrapped in a distinct visual identity.", year: "2026", role: "Frontend & full-stack developer", category: "Commerce · Brand system", featured: true, stack: ["React", "JavaScript", "E-commerce", "Auth", "Vercel"], links: { live: "https://luxe-smoky-mu.vercel.app/", repo: "https://github.com/0xEmmo/Luxe" }, problem: "Streetwear commerce needs to carry both product information and a point of view. A catalogue can be technically complete and still feel anonymous; this build needed the shopping path and the brand world to reinforce one another.", brief: ["Browse a product catalogue with enough detail to make a confident choice.", "Carry a customer from product to cart and checkout without losing the identity of the store.", "Provide auth and admin surfaces for the operational side of commerce."], decisions: shared.decisions, outcomes: [{ value: "Full", label: "catalogue to checkout experience" }, { value: "02", label: "customer and admin surfaces" }, { value: "Lagos", label: "brand and audience context" }], limits: ["Commerce details such as payments, fulfilment and inventory need continuous operational validation beyond the interface.", "The next layer is a stronger order history and more robust stock-aware product states."] },
  { slug: "ai-news-surface", index: "05", name: "AI News Surface", tagline: "An editorial workflow shaped around an AI pipeline", summary: "An AI-powered news reporting tool designed to move from story input to generated output with fewer manual steps in between.", year: "2026", role: "Frontend developer · AI integration", category: "AI · Automation tool", featured: true, stack: ["React", "JavaScript", "AI integrations", "Automation", "Vercel"], links: { live: "https://ai-news-surface.vercel.app/", repo: "https://github.com/0xEmmo/ai-news-surface" }, problem: "AI tools often make the generation step look magical while leaving the workflow around it vague. The useful question is not only what the model can write, but how a person reviews, directs and uses the result.", brief: ["Create a focused interface for moving from a story input to a generated report.", "Make the pipeline visible enough that the user understands what the tool is doing.", "Keep the product surface focused on useful output instead of model theatre."], decisions: shared.decisions, outcomes: [{ value: "AI", label: "integrated into a practical workflow" }, { value: "01", label: "focused reporting surface" }, { value: "Review", label: "human direction remains in the loop" }], limits: ["Generated content still needs editorial judgement and source verification.", "The next improvement is a richer history of generated reports and clearer provenance for inputs."] },
];

export const featuredProjects = projects.filter((p) => p.featured);
export function getProject(slug: string) { return projects.find((p) => p.slug === slug); }
export const otherRepos = [
  { name: "restaurant-pitch", note: "A focused pitch experience for a restaurant concept", lang: "Web", href: "https://lumistro-restaurant-pitch.vercel.app/" },
  { name: "urban-street", note: "Brand site for a street food business", lang: "Web", href: "https://urbanstreet.vercel.app/" },
  { name: "colosseum-idea-lab", note: "AI-generated startup ideas modelled after hackathon winners", lang: "AI / Web", href: "https://colosseum-idea-lab.vercel.app/" },
];
